-- Force delete all data by temporarily disabling RLS and foreign key checks
-- Run this in Supabase SQL Editor with elevated permissions

-- Disable RLS temporarily
ALTER TABLE posts DISABLE ROW LEVEL SECURITY;
ALTER TABLE threads DISABLE ROW LEVEL SECURITY;
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE topics DISABLE ROW LEVEL SECURITY;
ALTER TABLE forum_users DISABLE ROW LEVEL SECURITY;
ALTER TABLE thread_bookmarks DISABLE ROW LEVEL SECURITY;
ALTER TABLE thread_watches DISABLE ROW LEVEL SECURITY;
ALTER TABLE thread_votes DISABLE ROW LEVEL SECURITY;
ALTER TABLE post_votes DISABLE ROW LEVEL SECURITY;
ALTER TABLE thread_reads DISABLE ROW LEVEL SECURITY;
ALTER TABLE reputation_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE profile_customizations DISABLE ROW LEVEL SECURITY;
ALTER TABLE post_reactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE polls DISABLE ROW LEVEL SECURITY;
ALTER TABLE poll_options DISABLE ROW LEVEL SECURITY;
ALTER TABLE poll_votes DISABLE ROW LEVEL SECURITY;
ALTER TABLE best_answers DISABLE ROW LEVEL SECURITY;

-- Delete all data in correct order
TRUNCATE TABLE post_reactions CASCADE;
TRUNCATE TABLE poll_votes CASCADE;
TRUNCATE TABLE poll_options CASCADE;
TRUNCATE TABLE polls CASCADE;
TRUNCATE TABLE best_answers CASCADE;
TRUNCATE TABLE posts CASCADE;
TRUNCATE TABLE threads CASCADE;
TRUNCATE TABLE topics CASCADE;
TRUNCATE TABLE categories CASCADE;
TRUNCATE TABLE thread_bookmarks CASCADE;
TRUNCATE TABLE thread_watches CASCADE;
TRUNCATE TABLE thread_votes CASCADE;
TRUNCATE TABLE post_votes CASCADE;
TRUNCATE TABLE thread_reads CASCADE;
TRUNCATE TABLE reputation_events CASCADE;
TRUNCATE TABLE profile_customizations CASCADE;
TRUNCATE TABLE forum_users CASCADE;

-- Re-enable RLS
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE threads ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE forum_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE thread_bookmarks ENABLE ROW LEVEL SECURITY;
ALTER TABLE thread_watches ENABLE ROW LEVEL SECURITY;
ALTER TABLE thread_votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE post_votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE thread_reads ENABLE ROW LEVEL SECURITY;
ALTER TABLE reputation_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE profile_customizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE post_reactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE polls ENABLE ROW LEVEL SECURITY;
ALTER TABLE poll_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE poll_votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE best_answers ENABLE ROW LEVEL SECURITY;

-- Verify
SELECT 
  'threads' as table_name, COUNT(*) as count FROM threads
UNION ALL
SELECT 'posts', COUNT(*) FROM posts
UNION ALL
SELECT 'categories', COUNT(*) FROM categories
UNION ALL
SELECT 'topics', COUNT(*) FROM topics
UNION ALL
SELECT 'forum_users', COUNT(*) FROM forum_users;
